CREATE OR REPLACE PROCEDURE SNEAKERFAQTORY_MARINA.BRONZE.DIM_CURRENCY_INC()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
INSERT INTO SNEAKERFAQTORY_MARINA.BRONZE.T052
SELECT
    COALESCE(REPLACE(source.INDEX, ''.0'', ''''), ''-1''),
    COALESCE(source.CURRENCYID, ''N/A''),
    source.CURRENCY,
    source.LASTMODIFIED
FROM
    (SELECT $1 AS INDEX, 
    $2 AS CURRENCYID, 
    $3 AS CURRENCY, 
    $4 AS LASTMODIFIED
     FROM @SNEAKERFAQTORY_MARINA.STAGING.MARINA_STAGE  
     WHERE METADATA$FILENAME LIKE ''mssql_source/inc/T052%'' AND METADATA$FILENAME NOT IN (SELECT FILE_NAME FROM SNEAKERFAQTORY_MARINA.BRONZE.FILES_HISTORY) AND METADATA$FILE_ROW_NUMBER > 1
    ) source
LEFT JOIN SNEAKERFAQTORY_MARINA.BRONZE.T052 bronze 
    ON COALESCE(REPLACE(source.INDEX, ''.0'', ''''), ''-1'') = bronze.INDEX
    AND COALESCE(source.CURRENCYID, ''N/A'') = bronze.CURRENCYID 
    AND source.LASTMODIFIED = bronze.LASTMODIFIED
WHERE
    (
        bronze.INDEX IS NULL
        AND bronze.CURRENCYID IS NULL
    )
    OR (
        bronze.CURRENCY IS NOT NULL
        AND bronze.CURRENCY <> source.CURRENCY
    );

INSERT INTO SNEAKERFAQTORY_MARINA.BRONZE.FILES_HISTORY (FILE_NAME)
SELECT DISTINCT SPLIT_PART(METADATA$FILENAME, ''/'', -1) AS FILE_NAME
FROM @SNEAKERFAQTORY_MARINA.STAGING.MARINA_STAGE  (file_format => SNEAKERFAQTORY_MARINA.STAGING.CSV_FORMAT)
WHERE METADATA$FILENAME LIKE ''mssql_source/inc/T052%''
AND NOT EXISTS (
    SELECT 1
    FROM SNEAKERFAQTORY_MARINA.BRONZE.FILES_HISTORY fh
    WHERE fh.FILE_NAME = SPLIT_PART(METADATA$FILENAME, ''/'', -1)
);

MERGE INTO SNEAKERFAQTORY_MARINA.SILVER.CURRENCY AS target USING (
    SELECT
        source.*
    FROM
        (
            SELECT
                *,
                ROW_NUMBER() OVER (
                    PARTITION BY
                        INDEX,
                        CURRENCYID
                    ORDER BY
                        LASTMODIFIED DESC
                ) as row_num
            FROM
                SNEAKERFAQTORY_MARINA.BRONZE.T052
        ) source
    WHERE
        source.row_num = 1
) AS source ON target.ID = SHA2 (source.INDEX || source.CURRENCYID, 256) WHEN MATCHED THEN
UPDATE
SET
    target.CURRENCYNAME = COALESCE(source.CURRENCY, ''N/A''),
    target.LASTMODIFIED = source.LASTMODIFIED WHEN NOT MATCHED THEN INSERT (ID, CURRENCYCODE, CURRENCYNAME, LASTMODIFIED)
VALUES
    (
        SHA2 (source.INDEX || source.CURRENCYID, 256),
        source.CURRENCYID,
        COALESCE(source.CURRENCY, ''N/A''),
        source.LASTMODIFIED
    );

MERGE INTO SNEAKERFAQTORY_MARINA.GOLD.DIM_CURRENCY AS target USING (
    SELECT
        ID,
        CURRENCYCODE,
        CURRENCYNAME,
        LASTMODIFIED
    FROM
        SNEAKERFAQTORY_MARINA.SILVER.CURRENCY
    WHERE
        ID <> ''-1''
        AND CURRENCYCODE <> ''N/A''
) AS source ON target.ID = source.ID WHEN MATCHED THEN
UPDATE
SET
    target.CURRENCYNAME = source.CURRENCYNAME,
    target.LASTMODIFIED = source.LASTMODIFIED WHEN NOT MATCHED THEN INSERT (ID, CURRENCYCODE, CURRENCYNAME, LASTMODIFIED)
VALUES
    (
        source.ID,
        source.CURRENCYCODE,
        source.CURRENCYNAME,
        source.LASTMODIFIED
    );

COMMIT;

RETURN ''Successfully executed'';

EXCEPTION WHEN OTHER THEN ROLLBACK;

RAISE;

END;
';